import "./globals.css";
import { Plus_Jakarta_Sans, Open_Sans } from "next/font/google";

export const plusJakartaSans = Plus_Jakarta_Sans({
  subsets: ["latin"],
  display: "swap", // Mencegah Cumulative Layout Shift (CLS)
  variable: "--font-plus-jakarta-sans", // Nama variabel CSS untuk Tailwind
});

export const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-open-sans", // Nama variabel CSS untuk Tailwind
});

export const metadata = {
  title: "Sentinel Forces",
  description: "Generated by create next app",
};

if (typeof window !== "undefined") {
  gsap.registerPlugin(ScrollTrigger);
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${plusJakartaSans.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
